export const GET_CONTACTS = "GET_CONTACTS";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAILURE = "GET_CONTACTS_FAILURE";
export const RESET_CONTACTS = "RESET_CONTACTS";

export const UPDATE_SEARCH = "UPDATE_SEARCH";
export const UPDATE_ONLY_EVEN_FILTER = "UPDATE_ONLY_EVEN_FILTER";
export const UPDATE_PAGE = "UPDATE_PAGE";
export const INCREMENT_PAGE = "INCREMENT_PAGE";
export const UPDATE_COUNTRY = "UPDATE_COUNTRY";

export const AUTH_TOKEN =
  "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjE3MSwiZXhwIjoxNjM5NDY2NjE1fQ.9vE-glLQtV2NT3gNMkqeRkrWWZAhYCqX-_ibs7lC8GY";
export const DEFAULT_COMPANY_ID = 171;

export const COUNTRY_ALL = 0;
export const COUNTRY_US = 226;
